### ISSUE TITLE
Investigate persistent storage in Che

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#111]
In addition to having the persistent S3, having a persistent home directory is becoming more important especially if we have different types of workspaces.

**Comment by bsatoriu** [comment]
The use of shared volumes in Che today is limited to cross-component sharing, and only in Che 7. Components, in the context of Che, refer to the components comprising a particular workspace. These components are configured in the [Che "devfile"](https://github.com/redhat-developer/devfile). 

Support for cross-_workspace_ PVs is currently a [severity P1 issue](https://github.com/devfile/kubernetes-api/issues/19). As such, it should get included as a Che 7 feature once implemented. 

There is no built-in support in Che 6 for shared PVs in a K8S cluster configuration. One solution for Che 6 would be to use a utility like `rsync` to synchronize users' separate workspace volumes with a master volume during the workspace startup process. The advantage to this approach is that we could control the timeline of development. We could also implement a design that uses the `devfile`, or contribute one to the github issue referenced above.

If time permits, I would recommend implementing persistent storage after upgrading to Che 7 so that we can make use of the existing efforts to support this natively in the  devfile. This has the advantage of avoiding duplication of development effort.

**Comment by bsatoriu** [comment]
One edge case to consider for shared PVs is naming conflicts between projects. Consider a user who clones the same project in different workspaces. When using a single volume, we would need to partition projects by workspace either by creating subfolders or somehow identifying the workspace associated to its project(s).

**Comment by oddes** [comment]
As per Dev, there was no development activity involved and it is planning purposes.
