### ISSUE TITLE
[Data]: GLAD Landcover Dataset 2020

### ISSUE THREAD

**Issue by abarenblitt** [MAAP-Project/ZenHub#1134]
### Dataset Name

Global Land Cover and Land Use 2000 and 2020

### Dataset Description

Annual maps of land cover and land use (2020)
Global map with continuous measures of bare ground and tree height inside and outside of wetlands, seasonal water percent, and binary labels of built-up, permanent snow/ice, and cropland.

### Requestor Name/Affiliation

Abigail Barenblitt/ University of Maryland

### Platform/Method/Sensor

Landsat archive

### URL or DOI to Dataset Description

https://doi.org/10.3389/frsen.2022.856903

### URL to Download or Access the Data

https://storage.googleapis.com/earthenginepartners-hansen/GLCLU2000-2020/v2/download.html

### Data License

Creative Commons Attribution 4.0 International License

### Intended Science Use Case

Examining PA GEDI values by landcover tupe

### Format of the Data

GeoTIFF

### Additional Information

Currently only need 2020

**Comment by wildintellect** [comment]
The answer to this might not be to download anything, another group has made a single COG out of this dataset and hosted it publicly (we might want a copy later for repeatability).

Here's a notebook I put together showing how to extra points from the file using Terra in R, a single GEDI extracted tile from the GEDI_PA folder with 500,000 pts+ runs in less than a couple of minutes.
https://gist.github.com/wildintellect/87a9fc8fffa9c20e57a0f168845013f3

We'll still look into if we should officially pull a copy of the data into MAAP STAC. That would add a step of querying STAC for matching files, and then extracting across those.

**Comment by hrodmn** [comment]
If we have the time to build a stactools package for this dataset it would be a valuable addition since there are several other GLAD datasets that could be useful in the future. If nothing else it could be a nice layer for visualizations in MAAP maps.

I spent a few minutes on a [notebook](https://gist.github.com/hrodmn/b6caafc3503e80a876c5c2b6920f49bf) that uses `obstore` for I/O and `rio-cogeo` for converting a plain tif to a COG.

@wildintellect do you still want to load this dataset into the MAAP STAC? It could be a useful exercise for me while getting ramped up on STAC ingestion.

**Comment by hrodmn** [comment]
I rigged up a process for converting the raw data into COGs and uploading to the maap-ops-workspace shared directory. https://gist.github.com/hrodmn/2777fe84ca6af466791cdb9a66b62f66

They are not in the STAC yet but here is a notebook with the layers loaded in a leaflet map: https://notebooksharing.space/view/6af869282ffcfd9c097e364830ca528bd4320576712b553212627e83c92e2b68#displayOptions=hide-inputs

**Comment by hrodmn** [comment]
PR for a stactools package is open here: https://github.com/stactools-packages/glad-glclu2020/pull/2. @wildintellect  or @abarenblitt are you interested in reviewing it before I generate the STAC metadata for this collection?

**Comment by wildintellect** [comment]
@freitagb there's a question about if this should go to the MAAP STAC or the VEDA STAC since both projects might be keenly interested in the COG version of this dataset.

**Comment by hrodmn** [comment]
We are close to adding the GLAD LCLU dataset to the MAAP (or VEDA) STAC! Here is what I have done:
- built the stactools package: https://github.com/stactools-packages/glad-glclu2020/pull/2
- created a set of COGs from the original data (in the MAAP shared bucket)
  - [notebook](https://gist.github.com/hrodmn/2777fe84ca6af466791cdb9a66b62f66)
  - s3 key format: `s3://maap-ops-workspace/shared/henrydevseed/hansen/GLCLU2000-2020/v2/{year}/{loc}.tif`
  - tested out generating collection/item json using the stactools package
 
What's next:
- move the COGs to `s3://nasa-maap-data-store/file-staging/nasa-map/{collection_name}/`
- generate STAC metadata for the collections (`glad-glclu2020-v2` and `glad-glclu2020-v2-change`) and upload to the STAC database
- generate STAC metadata for the items and upload to the STAC database

I need some advice on a few things:
1. We need to pick a catalog to add this dataset to - MAAP or VEDA? I'm not sure it really matters for our users but we do have to pick one!
2.  I need to leave breadcrumbs for my COG generating procedure since I did it in a notebook in the MAAP ADE instead of using some more robust workflow. Where should I leave those docs besides this ticket?
    - Alternatively, I could try running the process (with STAC metadata generation built-in) in the Airflow way. I haven't done this before but my goal is to become familiar with the best practices for adding data to a STAC and that method keeps coming up as the standard approach. If there is a tutorial or example of how we run that process I would love to see it!
3. If we decide to just want to copy the COGs I will still need to run a process that generates STAC metadata and uploads it to the STAC database.

cc @jjfrench @ividito

**Comment by hrodmn** [comment]
I have ingested the whole dataset into the MAAP test STAC, PR for the COG and STAC generation notebooks is here: https://github.com/MAAP-Project/maap-documentation-examples/pull/67

If we want to put it in VEDA we can still do that, but for now it is in the MAAP test STAC.

Here is a notebook with map layers served from the STAC collection from titiler-pgstac: https://notebooksharing.space/view/4338e1efcfd0f8b2630b3832cda9c8ae5ef0926aa1f79bafcab10545e4f99474#displayOptions=hide-inputs

**Comment by wildintellect** [comment]
@hrodmn what's left to do before we pull it to the MAAP STAC ( officially not test )?

**Comment by hrodmn** [comment]
Once I get the go ahead I will run the stac generation notebook but pointed at the dev stac ingestor instead of the test ingestor.

**Comment by hrodmn** [comment]
I posted the `glad-glclu2020-v2` and `glad-glclu2020-change-v2` collections and items to the dev STAC database so they are ready to use!

https://stac.maap-project.org/collections/glad-glclu2020-v2
https://stac.maap-project.org/collections/glad-glclu2020-v2-change

**Comment by hrodmn** [comment]
I posted the glad-glclu2020-v2 and glad-glclu2020-change-v2 collections and items to the dev STAC database so they are ready to use!

https://stac.maap-project.org/collections/glad-glclu2020-v2
https://stac.maap-project.org/collections/glad-glclu2020-v2-change

**Comment by hrodmn** [comment]
Here is an example of how to use the STAC API to extract GLAD land cover values for a set of points in Python, following @wildintellect's example from above: https://gist.github.com/hrodmn/ecda7f64391bb77ed3c69528f9fb468a
