### ISSUE TITLE
Update Che configuration to support new EDSC URL search parsing

### ISSUE THREAD

**Issue by bsatoriu** [MAAP-Project/ZenHub#120]
Maya has made most of the changes to edsc extension to parse the url of edsc. In order to test it properly in the dev environment, she needs to have the Che EDSC proxy updated to point to the new version of edsc. Also, the message that is being posted in the proxy needs to change (this is currently where it’s sending the json object but needs to switch to sending the url).

**Comment by bsatoriu** [comment]
The Che proxy Apache config has been updated to send the updated EDSC iframe URL to its parent window. I also updated the message publishing to use location.href polling, rather than rely on the previous `onpopstatechange` event.

**Comment by oddes** [comment]
@gchang @mayadebellis 
EDSC URL search parsing is not copying to Che and currently, its throwing following error:
" Error making call to get search query. Have you selected valid search parameters?" 
I think is still pending to finish the following.
"Che EDSC proxy update to point to the new version of EDSC.

**Comment by mayadebellis** [comment]
@oddes Yes the parsing is currently not copying in Che on the dev cluster. This is actually the expected behavior with this change. Because @bsatoriu updated the proxy, it is now sending the new (correct) info but the extension on my end has not been updated yet to match that. It is waiting on this ticket: https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/maap-project/zenhub/71
