### ISSUE TITLE
Incorporate maap-py functions for MAAP API to ADE

### ISSUE THREAD

**Issue by echyam** [MAAP-Project/ZenHub#149]
with the `maap-py` library capable of handling calls to the MAAP API, we should standardize the ADE's calls by using the library

**Comment by echyam** [comment]
follow-on to #105

**Comment by echyam** [comment]
branch `maappy-for-maapAPI`
need to add new changes for register Algorithm to both jupyter extension and maap-py library

**Comment by oddes** [comment]
When I am doing Regression, I found following issues. Could u please confirm, so that we can open bugs for them.

1. When I try to register algorithm, pop-up is not coming. Please see the attached video to your slack [Unable to attach here due size]. 
Steps to Reproduce:

- clone the project.
- Try to open the notebook in workspace and try to register algorithm, you will be notified un committed files in the workspace error
- Now delete the notebook
- Now try again to register algorithm, you will see no error but pop-up never opens.

2. Is it possible to register same algorithm multiple time [Please see the screen shot]

![Screen Shot 2020-09-23 at 4.33.02 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/272d6c60-8e33-47bf-bf08-7bd7a6fab8ce)

3. When I am trying to delete above algorithm, I am getting the not found  error.

**Comment by echyam** [comment]
Re 2 & 3: Re-registering an algorithm overwrites the previous version.  There shouldn't be any duplicates.  I believe this was an error with syncing the MAAP API algorithm database and the DPS database.  It has been re-synced, and the issue will be fixed in the future, as @NamrataM and @bsatoriu are working on it.
