### ISSUE TITLE
Add a copy button to presigned URL and expiration selection

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#205]
The copy button would replace having to hold and drag the mouse all the way to the end of the url.

The expiration drop down should have:

- 24 hours (default)
- 1 week
- 1 month

**Comment by echyam** [comment]
on `develop`: Added expiration options in a dropdown menu and copy button
todo: make copy button nicer

**Comment by echyam** [comment]
TODO: remove copy button if no url

**Comment by echyam** [comment]
Create the s3 link as before (right-click file and select `Get Presigned S3 Url`
Before generating the link, the user gets a popup with the 3 expiration options:
<img src="https://user-images.githubusercontent.com/11476825/99013662-dd222a00-2505-11eb-9a8b-93e725e4b9ca.png" width="400"/>

The options can be modified here: 
https://github.com/MAAP-Project/maap-jupyter-ide/blob/59f77bfc9b216b7c20fbb875a650af04dddb2bee/show_ssh_info/src/funcs.ts#L197
Where the options are the duration in seconds, and human-readable version is in parentheses

**Comment by oddes** [comment]
@gchang would u able to assign these tickets to someone for the fix?
Currently, user able to see drop-down expiration duration field option but unable to get presigned s3 url since it is failing with the following error "Failed to get presigned s3 url" as shown in the attached screenshot.

![Screen Shot 2020-11-19 at 3.46.11 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/51828b97-7771-4ef4-85f8-c522dd610c0d)

**Comment by echyam** [comment]
@oddes  This bug should be the same thing I mentioned in #214 
Someone needs to check the workspace logs and see why the API is returning a 500.

**Comment by gchang** [comment]
See comment in #214

**Comment by oddes** [comment]
Copy button is showing as expected:
![Screen Shot 2020-12-01 at 2.27.54 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/c22141d4-a981-4155-8642-397290f353bb)
