### ISSUE TITLE
Review all plugins to ensure they still work with new Che 7 installation

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#227]

**Comment by mayadebellis** [comment]
@bsatoriu most things look great from my testing so far! Any updates on the cas stuff? Seems that is the main issue for the extensions so far

- ipycmc - :white_check_mark: 
- insert_defaults_to_notebook - :white_check_mark: 
- hide_side_panel - :white_check_mark: 
- user_meta_form - :white_check_mark: 
- maapsec - :white_check_mark: 
- dps_info - :white_check_mark: (requires extra login step to get all functionality)
- dps_magic - :white_check_mark: (requires extra login step to get all functionality)
- submit_jobs - :white_check_mark: (requires extra login step to get all functionality)
- edsc_extension - edsc loads but the rest of the extension is not working. Proxy needs to be set up
- show_ssh_info - not working. the ssh part of that is expected but this extension also includes s3 mounting. Mounts are also failing on loadUserInfo. Will look into this more but I assume it's related to the cas issues
- pull_projects - not working. Likely because of cas issues? The manual login after doesn’t help this extension because projects are only pulled on workspace startup. Also fails on loadUserInfo.

Curious if in show_ssh_info or places where we are querying the che API for user orgs etc if there are any issues with that changing. Hard to test much right now with the cas failures.

**Comment by mayadebellis** [comment]
Update:
-`edsc-extension` ✅ 
- `show_ssh_info`  ✅ Updated s3 mounts and ssh key injection to work in new environment.

- Last thing I need to do for testing is add a `gitlab_access_token` to my user profile to test pull_projects

**Comment by gchang** [comment]
@mayadebellis Is the `pull_projects` working?

**Comment by mayadebellis** [comment]
@gchang Yes it is!
