### ISSUE TITLE
Update GEDI Cal/Val Query data notebook (table is tree or plot, bounding box, fields)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#267]

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update GEDI Cal/Val Query data notebook (table is tree or plot, bounding box, fields)](https://trello.com/c/TDck2zf3/237-update-gedi-cal-val-query-data-notebook-table-is-tree-or-plot-bounding-box-fields)

**Comment by abarciauskas-bgse** [comment]
@spa0002 asked 

>When I looked at the notebook (https://nbviewer.jupyter.org/github/MAAP-Project/maap-documentation/blob/abarciauskas-bgse_gedi-demo/docs/source/query/gedicalval-demo_V1_F2F.ipynb), I see the following code "table":"plot" in cell [15]. I am looking at the Docstring for maap.executeQuery() but I do not see "table" in the Docstring. Do you know where info for table is?

@TonHai1111 @bsatoriu can you provide any guidance on the doc string for `executeQuery`? I haven't developed on maap-py in memory.

**Comment by TonHai1111** [comment]
You don't see the "table" in the maap.exectuteQuery() will send the query including the "table" information as a .json format. So here is how the json looks like (https://github.com/MAAP-Project/maap-py/blob/hai-modify-db-views/maap/maap.py#L341 - since this change is just a comment, I didn't do the PR, but will do now) when it will be send to query_service.py (in maap-api-nasa) and then query-postgres.ts (in maap-api-query-service). If you'd like to see how "table" is handled in query_service.py and query-postgres.ts, then here are the link:
- https://github.com/MAAP-Project/maap-api-nasa/blob/master/api/endpoints/query_service.py
- https://github.com/MAAP-Project/maap-api-query-service/blob/master/src/query-postgres.ts

**Comment by TonHai1111** [comment]
Just create a PR: https://github.com/MAAP-Project/maap-py/pull/15 for adding the description to the query. I leave it there a couple of days for any comment/suggestion before I will merge it. Thank you!

**Comment by spa0002** [comment]
GEDI Cal/Val Query data notebook updated, PR created and merged. Website updated with changes.
