### ISSUE TITLE
Deploy maap-api-query-service to GCC UAT

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/ZenHub#299]
Acceptance criteria:
* AWS Step function that outputs expected response to query to the GEDI cal/val database

Background:
* https://github.com/MAAP-Project/maap-api-query-service uses AWS Serverless Application Model for deployment and deploys a step function of 1 choice and 4 task states, the current deployment is in UAH and configured in the maap-api-nasa codebase here: https://github.com/MAAP-Project/maap-api-nasa/blob/master/api/settings.py#L64-L65
* A test input to test the step function execution should correspond to the message schema: https://github.com/MAAP-Project/maap-api-query-service/tree/13bae70e1e6355822143354e88bc71565de3d350#message-format
* Deployment script is in package.json: https://github.com/MAAP-Project/maap-api-query-service/blob/13bae70e1e6355822143354e88bc71565de3d350/package.json#L11

Tasks:
* @slesaad Git clone https://github.com/MAAP-Project/maap-api-query-service, configure AWS credentials for UAH "test" environment and attempt `npm run deploy`
* @slesaad or @chuckwondo identify how to add the gcc- permissions boundary as part of the IAM role deployed https://github.com/MAAP-Project/maap-api-query-service/blob/13bae70e1e6355822143354e88bc71565de3d350/template.yaml#L173-L195
* @chuckwondo Deploy to GCC UAT

Subsequent task:
* Incorporate into maap-data-system-services
* Test with RDS in GCC UAT

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deploy maap-api-query-service to GCC UAT](https://trello.com/c/XLbCS0qg/279-deploy-maap-api-query-service-to-gcc-uat)

**Comment by abarciauskas-bgse** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Replicate the gedi cal/val database in GCC UAT](https://trello.com/c/VTSl0wBm/275-replicate-the-gedi-cal-val-database-in-gcc-uat)

**Comment by slesaad** [comment]
Deploying and testing `maap-api-query-service`:
- clone the [repo](https://github.com/MAAP-Project/maap-api-query-service)
- install `aws sam cli` (sam: serverless application model)
- run `npm install`
- set environment variables `STAGE` and `NODE_ENV` (defaults: `dev` and `production` respectively)
- run `npm full-deploy` (builds, packages and deploys)
  (I had to create two buckets manually: `maap-api-query-service-${STAGE}` and `maap-api-query-service-${STAGE}-deploy`, because I was getting 's3 bucket doesn't exist` errors.)

Testing after deployment is successful:
- I executed the corresponding state machine: `maap-api-query-service-${STAGE}-RunQuery` with the following input:
```
         {
            "id": "sdfagsareryfgsadfadbyysre",
            "src": {
                "Collection": {
                    "ShortName": "GEDI Cal/Val Field Data_1",
                    "VersionId": "001"
                }
            },
            "query": {
                "where": {
                    "project": "usa_sonoma"
                },
                "bbox": [
                    -122.6,
                    38.4,
                    -122.5,
                    38.5
                ],
                "table":"tree"
            }
        }
```
- After the state machine successfully executed, I checked for results in bucket `maap-api-query-service-${STAGE}-query-results`, which seems to give a valid result

**Comment by abarciauskas-bgse** [comment]
This is great @slesaad and I think represents completion of your portion of the task. I think it would be helpful to automate your testing so when we deploy to GCC UAT we can easily test the deployment.

**Comment by abarciauskas-bgse** [comment]
Another "next step" which is more of a stretch is running a local instance of https://github.com/MAAP-Project/maap-api-nasa so we can test via the API /query endpoint, but there is more involved there (and a lot more I don't know about and if this approach will work) so that is more of a research task.

**Comment by slesaad** [comment]
The scripts for testing the deployment are added to the above [Pull Request](https://github.com/MAAP-Project/maap-api-query-service/pull/4).

**Comment by markdboyd** [comment]
@abarciauskas-bgse 

I have the query service deployed to GCC UAT as the `maap-api-query-service-uat` Cloudformation stack. I had to make changes to the deployment code to support GCC, mostly adding permissions boundary support, which are in this PR:

https://github.com/MAAP-Project/maap-api-query-service/pull/5

However, the automated test of the query service is failing because it is timing out trying to reach the database. I think this is probably some misconfiguration of the database VPC/subnets on my part, but would appreciate another pair of eyes when you get a second

**Comment by markdboyd** [comment]
This is working now. I had to update the RDS instance and Lambdas to use the same security group, `sg-04a8c7597537e80ef`, which is defined as follows:

Outbound rules

| Type | Protocol | Port Range | Destination |
|-|-|-|-|
| All traffic | All | All | 0.0.0.0/0 |

Inbound rules:

| Type | Protocol | Port Range | Source |
|-|-|-|-|
| PostgreSQL | TCP | 5432 | sg-04a8c7597537e80ef |
