### ISSUE TITLE
conda env no longer open by default in terminal

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#307]

**Comment by gchang** [comment]
@mayadebellis I believe this is a difference with Che 7 and persistent volumes, and we also have to be more careful given the shared persistent home directories with the new EFS setup.

The configuration once the docker image is built is that the `root` user is using `/projects` as its home directory. Inside `/projects`, it has folders like `.conda`, `.bash_profile`, etc that is loaded when you jump into the terminal. The expectation is that `/projects` is the same when you run the image, but it's not.

In Che 7, because of the persistent volumes, it uses `/projects` as a mount point upon startup. When you start workspace, one of the first things that happen is Che will do the equivalent of `mount /dev/something /projects`. Whatever you had in `/projects` when you built the image will be "hidden" by the mount. That's why it doesn't start conda. The `.bash_profile` is no longer there. What you probably will need to do is one of a few options:

1) Build everything in the docker image using the default `/root` home directory. Then, at the beginning of `entrypoint.sh`, run `usermod -m -d /projects root` which I think changes the home directory and moves the contents to the new location (see https://stackoverflow.com/questions/20797819/command-to-change-the-default-home-directory-of-a-user). 

or 

2) Have docker build the image using `/projects` as the home directory. Then at the very end of the build, move the files out of `/projects` to another location. Then at the beginning of `entrypoint.sh`, move it back to `/projects` which should be the mounted persistent volume.

An additional consideration with the EFS implementation is a user's home directory is persistent across all workspaces. That means when `/projects` is mounted when the workspace starts, it may already contain files and folders. If you were to relocate/copy over files from `/root` or elsewhere, it'll overwrite what's already there, which isn't desirable. You'll probably want to do a check at the beginning of `entrypoint.sh` to determine whether to relocate/copy files.

**Comment by mayadebellis** [comment]
@maya think about what here can/should/shouldn't persist - for example the /projects/ .ssh directory as well

**Comment by mayadebellis** [comment]
@gchang In gcc ops the conda env is now activated by default. Didn't change anything but things appear to be working on that front. Still may be other unexpected things across images with the persistent volumes but going to close this ticket
