### ISSUE TITLE
Requester Pays Support

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/ZenHub#321]
**Is your feature request related to a problem? Please describe.**
Some data that platform users want to access is cloud available but in requester pays buckets.

**Describe the solution you'd like**
Add permissions to AWS IAM user (ADE/DPS) allowing users Access to specific `requester pays` buckets
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::usgs-landsat",
                "arn:aws:s3:::usgs-landsat/*"
            ]
        }
    ]
}
```

**Describe alternatives you've considered**
Using a specific IAM user, and passing those credentials in to Workspaces/noteboooks/DPS for use by authorized users. This method is currently used, with an IAM user defined for this role in the UAH dev env. However, I'm not aware of a way to pass credentials to a DPS job to run as a different IAM user.

If each MAAP user had a unique IAM the policy could be applied there, however we were unable to demonstrate the ability to track costs per IAM on S3, which is an open Data Team issue.

Note: There should be a second ticket about supporting secure 3rd party credentials in ADE and DPS jobs for accessing external services for data.

**Additional context**
The current example to support the UWG ABOVE Boreal Biomass project is Landsat 8 available from USGS in AWS **us-west-2**
The region of the bucket matters, when it's the same region as the ADE/DPS the costs are no different than if the data was in the MAAP Data Store. We should not enable this in the development environments (UAH/JPL) unless those are move to **us-west-2**, however we should enable this in GCC which is **us-west-2**.

**Comment by gchang** [comment]
The easiest method of allowing requester pays is setting up the ADE/DPS EC2 instances to have the proper IAM roles. Access keys seem to be a sensitive topic when it comes to IT security, e.g. I can only get time-limited keys.

Have you tried setting up an EC2 instance on GCC, creating an IAM role that allows access to the `landsat` buckets, and tried to download a file with the ` x-amz-request-payer : requester` header? If you're able to do that, then we should be able to add that permission to the roles we have for the ADE and DPS.

One thing I would like to figure out is the workflow for this and how we keep track of which external buckets we have access to. There should be a process for users to ask for a requester pays bucket, MAAP would then vet it (namely, make sure it's in us-west-2), we'd add it to the IAM role, and then catalog/keep track of the bucket somewhere so that we and users know that MAAP has access.

Re: 3rd party credentials for ADE/DPS jobs. We've been able to demonstrate that with the EDL federated login to access data at other DAACs. I would be cautious about expanding to even more services at this point.

**Comment by wildintellect** [comment]
I have not tried in GCC yet, still working on getting access. I do have it working on the DIT - ADE using an IAM role defined in the UAH account, assigned to a test user. The permissions posted above are copied from the working IAM Role. I agree that assigning that role when launching specific jobs with the IAM makes sense. Doesn't solve how to allow ADE access, unless those instances can also be launched under different IAM.

FYI an aws cli s3 list with a --profile from a particular account is a much easier way to test if the requester pays is working. Though I get why assigning the IAM to the EC2 is more similar to actual use test. Will ask @chuckwondo @markdboyd or @abarciauskas-bgse to help me test in UAT.
`aws --profile maap-uwg s3 ls s3://usgs-landsat/collection02/ --request-payer`

If that's the case passing secrets won't be needed here, will bring up other 3rd party when it arises.

**Comment by gchang** [comment]
By default, workspaces inherit the IAM role that the host machine is on, so if the host EC2 instance has access to the bucket, then the workspaces themselves also have it. I went ahead and checked a workspace in our new ops deployment... and it worked!

```
(base) root@workspacee50vt6mh1u6grqoj:~# aws s3 ls s3://usgs-landsat/collection02/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
(base) root@workspacee50vt6mh1u6grqoj:~# aws s3 ls s3://usgs-landsat/collection02/ --request-payer
                           PRE level-1/
                           PRE level-2/
2021-02-19 17:06:26        565 catalog.json
2020-11-30 19:17:42       1767 landsat-c2l1.json
2020-11-30 19:17:42       1768 landsat-c2l2-sr.json
2020-11-30 19:17:42       1721 landsat-c2l2-st.json
2020-11-30 19:17:42       1886 landsat-c2l2alb-bt.json
2020-11-30 19:17:42       1780 landsat-c2l2alb-sr.json
2020-11-30 19:17:43       1733 landsat-c2l2alb-st.json
2020-11-30 19:17:43       1782 landsat-c2l2alb-ta.json
```

Even though it's not supposed to! The reason it worked is because the EC2 that hosts the workspace had read access permissions attached to its role for any valid bucket. What I wanted was access to only the buckets that is owned by the OPS account. I made a more restrictive policy to fix this for now, but yes, workspaces can access requester pays by just the IAM role if we allow it. I imagine we'd create specific policies to give access to vetted requester pays bucket that we know are in the same region.

**Comment by wildintellect** [comment]
+1 limit it to approved buckets in same region.

**Comment by abarciauskas-bgse** [comment]
Thanks for looking into this @wildintellect @gchang good information to have that the workspace has the same bucket permissions as the EC2 instance role and that requester pays flag is permitted for any valid bucket that role has access to (via the role policy, I presumed)

**Comment by wildintellect** [comment]
@gchang I'm currently testing this in GCC, and getting Access Denied. I am testing with `rasterio` though not direct AWS access. Did you test after making the policy more restrictive? is the usgs bucket mentioned on the allowed list?

**Comment by wildintellect** [comment]
Test, oh wait going to make sure rasterio is up to date...
```
import rasterio as rio
file_s3 = 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/044/025/LC08_L2SP_044025_20150812_20200908_02_T1/LC08_L2SP_044025_20150812_20200908_02_T1_SR_B2.TIF'
with rio.Env(AWS_REQUEST_PAYER="requester"):
    with rio.open(file_s3, 'r') as src:
        # list of overviews
        oviews = src.overviews(1)
        # get second item from list to retrieve a thumbnail
        oview = oviews[1]
        # read first band of file and set shape of new output array
        thumbnail = src.read(1, out_shape=(1, int(src.height // oview), int(src.width // oview)))
# now display the thumbnail
show(thumbnail)
```

**Comment by gchang** [comment]
@wildintellect I'm able to update the IAM roles for the machine so that the `aws s3 ls s3://usgs-landsat/collection02/ --request-payer` command works within the workspace. However, the rasterio command still fails. If rasterio is built on GDAL, then it's probably because of this issue. https://github.com/OSGeo/gdal/issues/4058

**Comment by wildintellect** [comment]
@gchang yes that's likely the issue, rasterio is a wrapper around gdal. Going to loop @vincentsarago to see if there are some ideas for fix/workarounds.

**Comment by wildintellect** [comment]
@gchang after looking at the GDAL ticket the [linked post](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) gives some clues to creating a session with sts temporary credentials. With a few ENV vars and config we can cache temp credentials locally as needed (maybe add a maap py function to initiate), then rasterio will find them and work.

**Comment by wildintellect** [comment]
Just noting [python example](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-api.html) any chance of getting those ENV variables passed in?
`AWS_ROLE_ARN` might be all we need
```
assumed_role_object=sts_client.assume_role(
    RoleArn="arn:aws:iam::account-of-role-to-assume:role/name-of-role",
    RoleSessionName="AssumeRoleSession1"
)
```

**Comment by gchang** [comment]
I quickly tested the code above in GCC ops and it's failing because it needs permissions to perform the sts assume role function. I'll have to double check later, but my instinct tells me that the admins probably prohibit users from enabling that. Doesn't seem like good security practice to allow that. If it were allowed, I'd write a web service that would generate new AWS keys on demand -- it would make certain things so convenient.

**Comment by wildintellect** [comment]
@George checked that STS assume role works, and created a role for this use case. @bsatoriu can you implement an api endpoint to return a credentials object, as shown in example below. Users will use that to setup their aws session with rasterio.
```
import rasterio as rio
from rasterio.session import AWSSession
from rasterio.plot import show
import boto3

sts_client = boto3.client('sts')
assumed_role_object=sts_client.assume_role(
    #Actual ARN hidden
    RoleArn="arn:aws:iam::??????:role/maap-bucket-access-role", 
    RoleSessionName="AssumeRoleSession1"
)
credentials=assumed_role_object['Credentials']
#pass this back from api

boto3_session = boto3.Session(
    aws_access_key_id=credentials['AccessKeyId'],
    aws_secret_access_key=credentials['SecretAccessKey'],
    aws_session_token=credentials['SessionToken']
)

aws_session = AWSSession(boto3.Session(), requester_pays=True)
file_s3 = 's3://usgs-landsat/collection02/level-2/standard/oli-tirs/2015/044/025/LC08_L2SP_044025_20150812_20200908_02_T1/LC08_L2SP_044025_20150812_20200908_02_T1_SR_B2.TIF'
with rio.Env(aws_session):
    with rio.open(file_s3, 'r') as src:
        # list of overviews
        oviews = src.overviews(1)
        # get second item from list to retrieve a thumbnail
        oview = oviews[1]
        # read first band of file and set shape of new output array
        thumbnail = src.read(1, out_shape=(1, int(src.height // oview), int(src.width // oview)))
# now display the thumbnail
show(thumbnail)
```

**Comment by gchang** [comment]
Will be closing this tix. The implementation of this is captured in #428.
