### ISSUE TITLE
workspace error "User's SSH Key undefined. SSH service unavailable"

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#333]
When I open workspace getting an error "User's SSH Key undefined. SSH service unavailable." could be with the ssh plug-in

**Comment by mayadebellis** [comment]
This is not an error - it is a warning (warnings are orange and errors are red). The plugin is working as intended here. This message is warning the user that the ssh service is not available because they do not have a key uploaded. If a user has an ssh key associated with their profile, they will not see this message.

**Comment by oddes** [comment]
Maya,
I have already uploaded my profile as shown below:
<img width="1674" alt="Screen Shot 2021-05-17 at 5 35 23 PM" src="https://user-images.githubusercontent.com/34038615/118572884-46455d00-b736-11eb-9eef-660fd777e5d2.png">

**Comment by gchang** [comment]
@bsatoriu Sri appears to have a ssh profile key already but it's not being propagated to Che.

**Comment by bsatoriu** [comment]
@oddes - I confirmed that the SSH key is propagating now on Ops using my account. Please re-try once more on ade.ops.maap-project.org using a new workspace. Thanks.

**Comment by oddes** [comment]
@bsatoriu 
I have tested in https://ade.ops.maap-project.org/ environment and it is working as expected and I am not seeing the error anymore.
