### ISSUE TITLE
GUI based opening of Earth Data search doesn't work

### ISSUE THREAD

**Issue by lauraduncanson** [MAAP-Project/ZenHub#337]
**Describe the bug**
When I go to 'Open Earth Data Search' via the GUI I get an error: '404 Not Found.'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abarciauskas-bgse** [comment]
@bsatoriu or @gchang perhaps we can look into this together? https://search.maap-project.org/search and https://www.maap-project.org/search/ seem to load fine but I was able to reproduce this error in ade.maap-project.org both using the "Data Search" dropdown and sidebar options to "Open Earthdata Search"

![Screen Shot 2021-05-24 at 11 34 19 AM](https://user-images.githubusercontent.com/15016780/119392013-ff9aba00-bc83-11eb-8a5b-4cecf895c4d0.png)

**Comment by gchang** [comment]
This has been resolved. The EDSC proxy on pilot ops environment wasn't running. The machine appears to have been rebooted about 2 weeks ago and the apache service didn't start up with it. I verified that EDSC is working in all the environments we have. We're making the proxy a kubernetes pod with tix #326 so that should handle restarts and certificate renewals automatically.
