### ISSUE TITLE
Check conda version in all of the base images

### ISSUE THREAD

**Issue by mayadebellis** [MAAP-Project/ZenHub#357]
The conda version should be consistent throughout so we know that the packages will behave the same in dps as they do in the user workspace.

The conda version should be 4.7.12 in all images as this is the version we start from in the original miniconda base image and is the final version the workspaces end up being. To ensure the conda version stays the same throughout a dockerfile on each conda install line specify `conda=4.7.12`. Installing packages all on one line can also help version consistency as pinned versions of packages can update in a later conda install line if it is no longer specified.

**Comment by wildintellect** [comment]
@gchang this is the follow on to ticket #322 
It's becoming a big headache, and we should come up with a plan to fix and/or flow for custom images.
To add to the above, not only should we be pinning packages with conda, but we should be tagging the ade images more often so that prior variants can be built, and dps jobs can be tied to specific image versions, not latest.

Workarounds: we are currently `pip install -U` many packages in workspaces and dps jobs to get things to run. 
This not working also completely blocks attempts to use pdal and entwine to work with EPT data, as these libraries require system libs, and conda normally handles that.
More examples, we are forcing the upgrade of rasterio to get bug fixes in latest releases, which also involves doing an `unset PROJ_LIB` so that the conda proj db is not used for rasterio and geopandas.
I suspect this is also where the numpy version issue crept in recently when the base image was rebuilt.

cc: @abarciauskas-bgse

**Comment by gchang** [comment]
We'll be releasing new images soon which will upgrade these libraries and be consistent across all environments.
