### ISSUE TITLE
Finalize Jobs UI Figma Wireframe

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#393]

**Comment by marjo-luc** [comment]
Comments from epic posted here for convenience:

Rework jobs ui to separate 'Submit Jobs' from 'View Jobs'. 'Submit Jobs' would be a modal that has the existing functionality, but also include an option to copy the generated code to the clipboard for users to paste into jupyter notebooks. 'View Jobs' would be a main area widget and would be reworked to leverage the react-table module which offers easy-to-use column filtering options.

Implementation of the extensive filters available from react-table will allow users to easily filter down to only jobs of interest, reducing the risk of being overwhelmed by potentially thousands of job records. We would also train users to use user-tags to make it easier to view batch jobs.

Do we want to remove the 'Delete' and 'Dismiss' functionality from the jobs ui? No longer permitting these would allow us to keep better provenance.

Investigate how to display job inputs and full traceback to users and provide more info in general without duplicating Figaro.

**Comment by anilnatha** [comment]
Comments/Issues from heuristic analysis:

- Input parameters should be marked as optional or required
- Submit job modal needs a close button (don't know if this is handled by the jupyterlab UI)
- Consider reordering columns for view jobs data grid (id -> status, time vs status -> id, time)
- Detailed information will be difficult to read if the amount of information in the expanded rows increases
- When a job fails, the UI doesn't provide a simple way for the user to retrigger or create a new job from an existing job
- Users must expand row to see detailed info (consider showing error on hover for status)
- It's not obvious is jobs are associated with one another (i.e. batched jobs vs one-offs)
- If thousands of jobs are entered the list will be very long and difficult to navigate
- Buttons in registering algorithm should be hidden if they have no action associated with the existing step (e.g. register button is shown on the config step)
- Delete buttons are colored gray instead of red
- When deleting an input parameter in the register algorithm screen, a confirmation dialog should be shown to avoid erroneous button clicks
- Additional documentation may be beneficial on the "register" screen
- How does the "previous" buttons work on the register algorithm screens after the process of registering an algorithm is triggered and after. Do the screens enter a "read" more state?
-

**Comment by anilnatha** [comment]
@NamrataM No rush, but when you have a moment could you send me the following:

- [ ] Sample Code to show in UI for "Copy to Jupyter Code" Feature
- [ ] Job metrics output sample that I can use to display in the View Jobs UI

Thank you!

**Comment by anilnatha** [comment]
@NamrataM When you have a moment, can you send me the info listed in my comment above.

@marjo-luc I've created a UI for the algorithm search and discovery addition to the jobs UI.  We just need to meet so we can review them and coordinate any additional changes that you recommend.

**Comment by anilnatha** [comment]
Reviewed UI with Marjorie and Namrata today. Additional changes are captured in comments in Figma.

**Comment by anilnatha** [comment]
1. Review implementation and make recommendations.
2. Rob/Anil to conduct usability testing with UWG to gather feedback and observe potential issues to improve UI/UX.

**Comment by gchang** [comment]
Still waiting on usability testing.
