### ISSUE TITLE
Improve reliability of S3 folders in workspaces

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#467]
Users report that folders frequently disconnect, especially when there are multiple users looking at the folder

**Comment by bsatoriu** [comment]
We increased the storage capacity on the ADE by 100gb (x3 nodes) to hopefully eliminate any kernel crashing while we work on a longer term solution:

Create an internal data management script that loops through ADE workspace pods, retrieves a list of stale cache data from the `/tmp` directory of pods' s3fs containers, and deletes any stale cache data. The criteria for stale data will be determined once we have analyzed several samples of s3fs temp data and performed some preliminary testing on cache removal in DIT.

**Comment by bsatoriu** [comment]
By testing a sample UWG notebook (see attached), I confirmed these S3 folder disconnects were caused by excessive disk use, combined with overly-lenient cull settings in our fscache configuration. 

The fscache on our ADE servers accounted for 75% of our disk usage in our ADE nodes on average. On inspecting the cached content, however, I found a large portion of the cache was quite stale and included workspace files over six months old. By reducing the caching limits from ~90% of disk space to ~40%, we retain the benefits of fscache while improving workspace stability. By increasing the storage headroom of each cluster node, disk pressure on the s3fs mounts is substantially lowered.

I tested this 40% culling configuration on the attached notebook, and was able to execute each cell to completion. Using the default 90% culling configuration, however, the sample notebook would consistently fail (i.e., the `shared-buckets` folder disappears) at or before the cells shown in the attached screenshot:
![Screen Shot 2021-12-03 at 11 33 23](https://user-images.githubusercontent.com/27687558/145910863-9d27e802-8d49-43dd-8ead-8e122b191adc.png)

## Testing notes

- I installed metrics server to get accurate monitoring of CPU and memory: https://github.com/kubernetes-sigs/metrics-server. This is quite useful for monitoring the CPU and memory usage on both a node and pod basis.
- The memory status bar in the bottom of our Jupyter notebooks is, at times, far lower than the memory reported by the metrics-server. I believe the delta is the result of memory usage of the workspace's s3fs container, but need to confirm.
- In addition to modifying the fscache settings, we may consider limiting the workspace's `/tmp/` cache usage using a cron job or other utility as a scalability measure.

**Comment by oddes** [comment]
I can run the note book with no issues.
