### ISSUE TITLE
Profile page in UAT is not working.

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#475]
Steps to Reproduce:

1. Login to https://uat.maap-project.org/ as a NASA or ESA User
2. Go to Profile Page, you will notice that as user is not logged in, Please see the screenshot.![Screen Shot 2021-10-20 at 9.22.00 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/f30c7334-398d-4674-9ac9-d452f6859807)

**Comment by anilnatha** [comment]
Issue also exists in OPS.  Currently unable to login to DIT to verify if issue exists in that environment.

**Comment by anilnatha** [comment]
Have verified the issue exists in DIT, UAT, and OPS.

**Comment by anilnatha** [comment]
@bsatoriu I think another working session may be in order.  Since our first discussion I have:

1. Removed the latest version of the Authorizer plugin from DIT.
2. Deployed the Authorizer plugin using the fork we have at https://github.com/MAAP-Project/authorizer
3. Double checked the WordPress settings after installing our fork of the plugin
4. Inspected various log files in `/var/log/apache2` to see if any PHP errors were being thrown.
    1. One error was found regarding the use of `CURLOPT_GET` which I have fixed on DIT in the `maapprofile.php`
    ```
    [Mon Dec 13 21:48:33.661750 2021] [php7:warn] [pid 6450] [client 128.149.249.117:62638] PHP Warning:  Use of undefined constant CURLOPT_GET - assumed 'CURLOPT_GET' (this will throw an Error in a future version of PHP) in /var/www/dit.maap-project.org/wp-content/themes/monochrome-pro/page-templates/maapprofile.php on line 45, referer: https://dit.maap-project.org/
    ```
    2. NOTE: When authenticating to gain access to ADE, the `api.dit.maap-project.org.error.log` is being updated, but I don't see anything like this when the user's WordPress session is established via CAS.

I'll give it more thought tonight, but the issue is stumping me atm.

**Comment by anilnatha** [comment]
@bsatoriu Last night I remembered a comment you made about modifying the `functions.php` file to trigger the creation of a session. The lines needed for this were missing from this file, possibly due to theme upgrades.  I added the necessary code and the profile page is now working.

I've begun researching the following changes needed to prevent this from happening in the future:

* Create a child theme so that the changes to `functions.php` are not lost when the theme is upgraded.
* Modify the forked version of the Authorizer plugin so that it can't be upgraded through WP. This would require us to manually merge in changes from newer versions.

**Comment by anilnatha** [comment]
Profile page is working in DIT.  There was an issue in DIT with uploading a user key that Brian and I resolved.

I published the changes to UAT and while the profile page now displays after logging in, the uploading of a user key is not working.  I inspected the logs and the issue has something to do with a database call and is documented in the `api.uat.maap-project.org.error.log` file.  This issue in UAT is different from the issue we encountered on DIT and will require more time to investigate.

**Comment by anilnatha** [comment]
@bsatoriu While reviewing the `/var/log/apache2/api.uat.maap-project.org.error.log` log on UAT, I found a [potential] reason why the uploading of user keys is failing.  These two lines report that the database doesn't have a column named `urs_token`.

```
[Tue Jan 04 22:00:07.298437 2022] [wsgi:error] [pid 14779] [client 54.70.136.24:56014] sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column member.urs_token does not exist
[Tue Jan 04 22:00:07.298440 2022] [wsgi:error] [pid 14779] [client 54.70.136.24:56014] LINE 1: ...fied_date AS member_public_ssh_key_modified_date, member.urs...
```

The `/api/models/members.py` file of the `maap-api-nasa` codebase deployed to UAT differs from what is deployed to DIT. It references a property named `urs_token` which leads me to believe that a branch other than master is deployed to UAT which differs from what is deployed on DIT.

Resolving this code discrepancy issue will allow me to do further testing to ensure there are no other issues, but I don't know if pushing the master branch of the API codebase is the best solution. Don't want to trample on any one else's work that may be in progress with the API.

**Comment by bsatoriu** [comment]
@anilnatha I updated the UAT database scheme to include the member.urs_token. This is ready to re-test. Thank you!

**Comment by anilnatha** [comment]
@bsatoriu Thank you for pushing the update out, I'll re-test and report my findings.

**Comment by anilnatha** [comment]
Tested the upload key feature on UAT and it is working properly.  We can move this to QA now.

**Comment by oddes** [comment]
@anilnatha ![Screen Shot 2022-01-24 at 3.29.21 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/76a51657-f9ca-43bd-b8f5-ea4d4bceb7b6)

why the email id is showing multiple times:

**Comment by anilnatha** [comment]
Hi @oddes 

Good catch, odd that some fields repeat and others do not. I will investigate and report back.

**Comment by anilnatha** [comment]
Hi @oddes. I reviewed and updated the code that output user information to remedy the problem.  The issue has been fixed in DIT and UAT. Please test again.

**Comment by oddes** [comment]
@anilnatha  its fixed in DIT and UAT.
