### ISSUE TITLE
Enable User Metadata Form

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#491]
The User Metadata Form plugin was disabled on 9/2021 because it failed to build, producing typescript-related errors. Users are interested in having it reenabled. If we want to proceed with this, we may want to update the plugin with the latest code, which seems to be here: https://github.com/MAAP-Project/user-metadata-form

Commit disabling the plugin:
https://mas.maap-project.org/root/jupyter-image/-/commit/1c983c4e8519e7ecbe9cae94ba9f063c20dff45e

Sample failure log:
https://mas.maap-project.org/root/jupyter-image/-/jobs/2752

**Comment by marjo-luc** [comment]
Looping @abarciauskas-bgse and @NamrataM on this since it looks like there are a couple tasks touching this code base and I want to make sure I'm updating the plugin according to expectations.

**Comment by abarciauskas-bgse** [comment]
The latest code https://github.com/MAAP-Project/user-metadata-form is fine, however I'm not sure that the jupyter image would need to know anything about the user metadata form codebase itself since I think the plugin should just point to the form deployed at https://questionnaire.maap-project.org, but I don't know much about how the plugin works or what tests are being run. 

cc @philvarner who is working on automating deployment of the user metadata form. But, just to clarify, I would have guessed that the plugin doesn't need to know anything about the form's codebase or how its deployed so Phil's work should be unrelated to deploying the plugin to link to it.

**Comment by philvarner** [comment]
@marjo-luc The code for the the UMF web app is in [MAAP-Project/user-metadata-form], but the code for the Jupyter plugin is in [https://github.com/MAAP-Project/maap-jupyter-ide/tree/master/user_meta_form], so I think the compile errors just need to be fixed in the plugin.

**Comment by philvarner** [comment]
I believe the underlying issue is that the user-meta-form plugin package.json explicitly specifies the Typescript version:

```
  "devDependencies": {
    "rimraf": "^2.6.3",
    "typescript": "~3.5.3"
  }
```

None of the other packages do this, so the build explicitly must be a typescript 3.5.x build. A recent change in @types/node (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/55430) no longer allows the latest version of it (specified as `    "@types/node": "^14.0.14",` in the package.json) to be compiled with 3.5.x as it uses an assertion feature only available in 3.7.x. 

This gets reduced to just the error message `error TS1144: '{' or ';' expected.` in the GitLab Docker build output, but bulidling locally with verbose output shows that the "asserts" modifiers are causing this syntax error:

```
node_modules/@types/node/assert.d.ts:66:94 - error TS1144: '{' or ';' expected.

66         function strictEqual<T>(actual: any, expected: T, message?: string | Error): asserts actual is T;
                                                                                                ~~~~~~

node_modules/@types/node/assert.d.ts:66:101 - error TS1005: ';' expected.

66         function strictEqual<T>(actual: any, expected: T, message?: string | Error): asserts actual is T;
```

So, I think the simple fix is to just remove the typescript version specifier from the package.json and allow it to build with the same newer version that the rest of the plugins are (likely) building with.

**Comment by abarciauskas-bgse** [comment]
Thanks for finding https://github.com/MAAP-Project/maap-jupyter-ide/tree/master/user_meta_form @philvarner, and just for future reference I see that the only thing that looks specific to the questionnaire are these lines: https://github.com/MAAP-Project/maap-jupyter-ide/blob/master/user_meta_form/src/index.ts#L51-L53 (just in case I want to recall how to build a similar plugin in the future)

**Comment by marjo-luc** [comment]
Thank you for the input! I wasn't quite sure how these two repos were related, but I now have a good understanding.

**Comment by marjo-luc** [comment]
Made several fixes to get this plugin back up. It's been deployed on DIT and is available on OPS as **mas.ops.maap-project.org/root/jupyter-image/vanilla:develop_db**

**Comment by marjo-luc** [comment]
Made several fixes to get this plugin back up. It's been deployed on DIT and is available on OPS as **mas.ops.maap-project.org/root/jupyter-image/vanilla:develop_db**

**Comment by oddes** [comment]
Works as expected.
