### ISSUE TITLE
EDSC is not working as expected.

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/ZenHub#523]
Steps to Reproduce:

1. Open ADE workspace in UAT Environment.
2. Open EDSC
3. Search with spatial coordinates as shown in the attached screenshot, you will see search results.
4. Now, copy the query to ADE, you will notice the query and coordinates are not part of the query 

![Screen Shot 2022-03-16 at 2.27.45 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/5704a312-946a-45f0-87b1-3523fa0c95f6)

**Comment by bsatoriu** [comment]
I verified the maap.py EDSC url mapper is working correctly in UAT.

There have been a number of updates to the EDSC query mapper since our last EDSC extension update. This file, in particular, has introduced changes in many parameter data types (e.g. bounding box or 'sb' has changed from string to array):

https://github.com/nasa/earthdata-search/blob/master/static/src/js/util/url/url.js (last commit Mar 15 2022)
https://github.com/MAAP-Project/maap-jupyter-ide/blob/803ef8e183bb080f32ffe6f4485846007868ee58/edsc_extension/src/urlParser.js (last commit Aug 21 2020)

@marjo-luc I found this new repo that seems to replace the earlier EDSC extension: https://github.com/MAAP-Project/edsc-jupyter-extension. Is this ticket already being addressed there?

**Comment by marjo-luc** [comment]
@bsatoriu No, it is not. The new extension (https://github.com/MAAP-Project/edsc-jupyter-extension) is a jupyter_v3 conversion of the old extension. Any issues with the old extension would likely need to be carried over to the v3 extension. 
None of the v3 extensions can replace their older counterparts until UAT and OPS are updated to jupyter_v3.

**Comment by gchang** [comment]
Need to synchronize EDSC code into our EDSC parsing code.

**Comment by grallewellyn** [comment]
I will look into this issue once I get edsc extension running locally for me. My current error with edsc running locally is that after I launch EarthData Search, I am unable to click anywhere else on the screen, therefore I cannot see the results of a pasted query into a jupyter notebook. Marjorie is helping me with this issue and more details can be found here: https://app.zenhub.com/workspaces/maap-platform-5ee7f0d1f440de0024cd359b/issues/maap-project/zenhub/610

**Comment by gchang** [comment]
Related to #610

**Comment by grallewellyn** [comment]
Resolved. Request now looks like this 
`# generated from this EDSC search: https://ade.dit.maap-project.org:30052/search?p=!C1214470488-ASF&pg[1][v]=t&sb[0]=0.14063%2C13.21875%2C18.70313%2C22.64063&lat=0.0703125&long=0.140625
maap.searchCollection(bounding_box="0.14063,13.21875,18.70313,22.64063", has_granules_or_cwic="true", page_num="1", concept_id="C1214470488-ASF", limit=100)`

Might keep this issue open until I test this in DIT?

**Comment by grallewellyn** [comment]
Resolved in version 1.0.3 and tested in DIT to work
Also added to test rails
