### ISSUE TITLE
User changed email address in URS, changes don't appear to propogate through MAAP

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#571]
User email changes in URS don't get updated in our members database, ADE prompts for a profile update, and Gitlab probably has old info too.

**Comment by oddes** [comment]
ADE Steps:
1. Login to MAAP portal with userid
2. Navigate to ADE
3. Change the user email id on the URS.
4. Now, try to login to MAAP portal, works as expected
5. Navigate to ADE, first it will redirect to screen with : Update Account Information, even you update, it wont work. [hard stop] need a fix to 
   "It's keycloak in the ADE that's causing issues. When a user is created, keycloak uses the email address as the unique ID"

GitLab:
Same issue, will redirect to following screen:  need a fix
![Screen Shot 2022-07-31 at 9.26.27 AM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/3fe25648-3cfc-4a96-8e0a-61184d6756d2)

workaround:
User need to update URS email id to make it work.

**Comment by bsatoriu** [comment]
@oddes the ADE and GitLab issues are ready to be verified in Ops. I updated the Keyloak login flow to permit the auto-creation of new accounts upon URS email changed. Make sure to choose the "Review Profile" option in ADE when signing in with an account containing a newly changed email.

Since the last CAS deployment two weeks ago, I am now able to login to GitLab as well after changing my URS email.

**Comment by oddes** [comment]
Thanks Brian. Updated email on the URS side is not reflecting on MAAP profile page.

**Comment by bsatoriu** [comment]
@oddes I've updated the CAS service to synchronize any URS profile info (email, name, organization) upon login. 

This is ready to test on UAT.

**Comment by oddes** [comment]
Looks good in UAT.
![Screen Shot 2022-10-13 at 12.09.48 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/2b8857d7-7468-424d-b03a-d14460db38ee)

**Comment by oddes** [comment]
@bsatoriu 
Update email id shows on the profile page but login to ADE and GIT not working.

**Comment by oddes** [comment]
@bsatoriu it does not work when we dont change the Userid, which needs to be fixed.

**Comment by bsatoriu** [comment]
@oddes 
I was able to update the "account already exists" flow to send the user a confirmation email and proceed to the verification step. I also simplified the flow so that Keycloak automatically tries adding the user to the existing account.

These fixes led me to a new issue that is caused by a known Keycloak bug in the version, 4.8.3.Final, that we're currently using.

https://issues.redhat.com/browse/KEYCLOAK-8223

To fix *this* bug, I had to create a Postgres patch by adding a trigger to address the PK violation: https://github.com/MAAP-Project/keycloak-cas-services/blob/master/keycloak_patch.psql

This is now ready to re-test on UAT. To properly test this, please take the following steps:

1) Use two URS accounts with email addresses that have never been used in UAT. This is necessary because the Eclipse CHE API will store old emails you may have tested with, leading to database conflicts.
2) You need to have access to the FIRST email address you login with. This first email will be used to verify your SECOND email upon login to the ADE.

**Comment by oddes** [comment]
@bsatoriu 
1. it is working as expected for the ADE.
2. Git Repositories link is re-directing to service error, need to be fixed. Please see the attached image:
![Screen Shot 2022-11-14 at 2.40.20 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/f6a373b9-c05c-4bc3-8117-dd41c751e02a)

**Comment by bsatoriu** [comment]
@oddes Thanks Sri. I see the link to GitLab from the UAT portal was incorrect. I fixed the link so that it goes to the correct Git Repository. Please re-test once more when you're ready.

**Comment by oddes** [comment]
@bsatoriu  Great. All the links working now as expected!.
