### ISSUE TITLE
Clean out Algorithm Registration entries in Jupyter menus

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/ZenHub#696]

**Comment by rtapella** [comment]
Once the new Algorithm Registration UI is in place we can remove a bunch of stuff from the DPS menu. Maybe even trash the entire menu. Perhaps the "getCapabilities" menu entry should be put into the new registration/catalog UI somewhere?

![Screenshot 2023-03-20 at 9.49.35 AM.png](https://images.zenhubusercontent.com/61dc908470b3029fc627fcbb/6a23d779-c152-48ac-9a16-22620db9b7e4)

**Comment by rtapella** [comment]
Perhaps the "getCapabilities" menu entry should be put into the new registration/catalog UI somewhere?

Or maybe it should just go into revised documentation and be easier to find.

**Comment by marjo-luc** [comment]
The entire DPS/MAS menu has been pulled out for workspaces running jupyter v3.6 since most of these options are available through the Jobs UI. Those that aren't (the publish and delete options) will be available through the new algorithms UI, though are currently available in jupyter v3.6 workspaces through the maap-py client.
