### ISSUE TITLE
Fix delete button in workspace > overview

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#711]
Manually disabling pointer-events: none in the css fixes it

**Comment by anilnatha** [comment]
**** Additional documentation to support testing ****

Screenshot showing confirm dialog box that experiences the issue.

This is confirm dialog box is shown after a user clicks on the name of a workspace to view the workspace details, then clicks the delete button.  The issue is _not_ present on the workspace deletion dialog shown from the workspace listing page.

<img width="1003" alt="Screen Shot 2023-05-10 at 12 13 58" src="https://github.com/MAAP-Project/eclipse-che-dashboard/assets/931107/fe59a1ea-dcad-43f8-9c5c-359f76822b40">

**Comment by anilnatha** [comment]
Verified fix is working in DIT, need to promote to UAT.

**Comment by anilnatha** [comment]
Verified fix is working in both OPS environments; however, want to note that new OPS required a hard refresh to fetch updated css; whereas both UAT and DIT did not.
