### ISSUE TITLE
New workspaces have option to start R kernel even when it doesn't have a kernel

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#719]

**Comment by gchang** [comment]
This was a "me" problem. Jupyter looks for kernels in various locations. If at anytime one installs a kernel as a user, it'll install a definition in /project/.local/share/jupyter/kernel. For me, I guess I had run an older workspace that installed the r kernel as a user, which wrote to that location. Since /project is persisted, when I launched a non-r workspace, it still read the kernel definition from my home directory, but couldn't launch the R interpreter because it wasn't installed.

**Comment by rtapella** [comment]
Is this something we should try to fix for anyone else who had that older R workspace?

—
Rob Tapella
818-393-8030
________________________________
From: George Chang ***@***.***>
Sent: Monday, May 15, 2023 9:42:55 PM
To: MAAP-Project/ZenHub ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [MAAP-Project/ZenHub] New workspaces have option to start R kernel even when it doesn't have a kernel (Issue #719)


This was a "me" problem. Jupyter looks for kernels in various locations. If at anytime one installs a kernel as a user, it'll install a definition in /project/.local/share/jupyter/kernel. For me, I guess I had run an older workspace that installed the r kernel as a user, which wrote to that location. Since /project is persisted, when I launched a non-r workspace, it still read the kernel definition from my home directory, but couldn't launch the R interpreter because it wasn't installed.

**Comment by gchang** [comment]
If it becomes an issue, we know the solution. But I'm not sure what else is stored in that kernel folder since I'm not an active R user.
