### ISSUE TITLE
Integrate `stac_ipyleaflet`

### ISSUE THREAD

**Issue by anilnatha** [MAAP-Project/ZenHub#725]
The development of [stac_ipyleaflet](https://docs.pypi.org/organization-accounts/org-acc-faq/) package has run into an issue during testing where installation of the package using pip in a running basic stable workspace produces an error.

Running the following code results in a "model not found" error:

```
# Import the stac_ipyleaflet package
import stac_ipyleaflet
m = stac_ipyleaflet.StacIpyleaflet()
m
```

I encountered a similar issue when I was testing the installation of `ipyleaflet` which was resolved by installing the package during image builds. So the proposition here is to install `stac_ipyleaflet` during the image build process to determine if the error still exists. We'll use the pangeo image as our integration starting point, and if that works, we'll apply the change to our other workspaces as well.

In addition, @wildintellect shared with me that there are packages missing in our pangeo workspace that need to be added to our JupyterLab3 `environment.yml` based on the [requirements.txt](https://github.com/MAAP-Project/stac_ipyleaflet/blob/main/requirements.txt) file from stac_ipyleaflet:

```
ipyevents
pydantic
shapely
rio_tiler
rioxarray
xarray
pystac_client==0.6.1
```

Note: `rio_tiler` and `pystac_client` will need to be installed via pip.

**Comment by wildintellect** [comment]
Current solution was to install `stac_ipyleaflet` as part of the workspace image. Currently this has been done using the `pangeo` workspace so that we could get a beta out quickly.
https://github.com/MAAP-Project/maap-workspaces/pull/36#event-9353172924

This does appear to be working for users. Long term we'll need to test how to upgrade, and eventually come up with a plan to roll the package to other workspaces.
