### ISSUE TITLE
Create new EC2 instance for Auth

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#82]

**Comment by bsatoriu** [comment]
@gchang looks like I am not yet authorized to create new EC2 instances in GCC. when I try to launch a small instance in Ops, I am met with the following error:

**Launch Failed**
You are not authorized to perform this operation. Encoded authorization failure message: 9ngGQtlJOoHQ0qxLIrvwXys85GmBN-sZiwXILwL5RCO8_HDod2fj-e2aockCPzQQORO7ecaZV1E6kM7gJ-b3nvjp-aWjql2HfqBjpjO4vkzmHZpaI3zRA5NsYWKhUm3ZNt_1JxlA7lOJxlfrPXCdAEQuTYzGLM32hZBvBFFmSLIWTRVL93N3twklMCdzphftCqt290gWnRdA15rFfAhICDKDV_kJH2JhmZok9orvMzHnZa4QFyGYTu_kveFlSdflxuldYWk-npcPXXaKSmnqeQK59KhQ8r2pN5hg93dw3dRVRQLiMW5dn5z40PWv3RXilylruVDAMAgYIyTJMswnbYy-5o8ONgB0qCPokZvsQHBGIzLnlRA0ycxxZD6Iv3hxJrUhm0fCe66KommYTP6Xx0tNQsPxoe4SNKWaUrhrlNLsG5odQ7kZWcCaglBe0N5sF7FfaHwbbkVdrqUkPZ2R7JQlY-

In the sandbox environment, I am unable to launch an EC2 instance due to the absence of VPCs or subnets on the account,

**Comment by gchang** [comment]
GCC has its own set of images, you'll need to select it from "My AMIs" and choose "AMIs Shared With Me" (or something similar to that). Just choose the latest version of Ubuntu. They're automatically built every week or so.

**Comment by bsatoriu** [comment]
Thanks @gchang , I'm all set now.

**Comment by bsatoriu** [comment]
The Auth EC2 instances has been created in the GCC sandbox env: 
Instance Id: `i-00830f69479d8bf8a`
Instance type: `c5.xlarge`
Public IP: `52.25.47.49`

**Comment by oddes** [comment]
EC2 instance is up and running, as expected.
