### ISSUE TITLE
Libarchive error trying to run conda commands 

### ISSUE THREAD

**Issue by grallewellyn** [MAAP-Project/ZenHub#860]
Somehow is it becoming corrupt or something or related to the conda version? I create a new workspace and get
```
(base) root@workspacexhlnnq3hes11z537:~# conda --version
conda 23.7.4
```
then successfully run `conda env update -n base --file /projects/r_env.yml `However, if I run `conda env update -n base --file /projects/r_env.yml` again I get the libarchive error and the conda version is 23.9.0
I am testing this with 'mas.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:v3.1.1'
And there is similar behavior in DIT which is the new release

r_env.yml is
```
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - r-rcurl
  - r-devtools
  - r-rgeos
  - r-raster
  - r-rgdal
  - r-geosphere
  - r-RColorBrewer 
  - r-gdalUtils
  - r-snow 
  - r-plyr
  - r-maptools
  - r-scales
  - r-sf
  - r-sp
  - r-foreign
  - r-geojsonio
  - r-aws.s3
  - r-terra
  - r-aws.ec2metadata
```
See more information in #uwg on MAAP slack

**Comment by anilnatha** [comment]
The resolution for the libarchive error was to create custom conda environments for each our workspaces.  The libarchive error was occurring due to changes that were being applied to the `base` conda env.  We took this action after learning that making changes to the `base` conda env is not advised and leads to issues like what we experienced.
