### ISSUE TITLE
Update ADE recovery scripts and deploy Che 6 on TEST

### ISSUE THREAD

**Issue by gchang** [MAAP-Project/ZenHub#90]
Was: Create new ADE recovery scripts based on new cluster configuration

Re-using this ticket since the current task is an evolution.

**Comment by gchang** [comment]
Decided on not using a cluster configuration for Che 6. Will reuse existing recovery scripts for GCC deployment and then revisit this when we deploy Che 7 on Kubernetes.

**Comment by gchang** [comment]
Reusing ticket

**Comment by bsatoriu** [comment]
@gchang 
Now that [Che 6 is deployed to GCC](https://ade.uat.maap-project.org/) I'm working on installing the MAAP API on our GCC UAT server, so that I can finish setting up Keycloak. Then I'll get the MAAP stacks configured, at which point the deployment will be fully functional. There is another 5-8 points of work left. Let me know if you prefer this to be broken up into a different story. I expect to be done by tomorrow.

**Comment by bsatoriu** [comment]
Bumped up story points to account for GCC security-related research.

**Comment by bsatoriu** [comment]
@gchang the ADE is fully functional on GCC with a couple exceptions: 

1.  S3 mounted directories within workspaces. @mayadebellis do these still require aws keys on the ADE host machine? 
2. I am pointing to mas.maap-project.org from GCC ADE, not the GCC MAS at mas.uat.maap-project.org, as I wasn't sure if this is fully ready.

On our GCC ADE environment, I have set up the EDSC integration (the latest version), imported all the custom MAAP stacks, configured the 'Ready-to-go' options, and configured all the other dependencies (CAS, Syncope, API). Feel free to test it out when you get a chance. I have imported all of the Syncope accounts from JPL Ops.

https://ade.uat.maap-project.org/

**Comment by gchang** [comment]
Awesome ! @echyam may know more the S3 mounts. Using s3 endpoints, there isn't a need to use access keys to read/write to the workspace bucket. I'll work on the GCC MAS some more today. The registry and gitlab are there -- what's missing is the runner to build the images.

**Comment by echyam** [comment]
@bsatoriu we only need the keys because we needed auth from 2 different AWS accounts.  
If the host machine has the IAM permissions for both the S3 buckets storing DPS job outputs and the cumulus granules, then we don't need any keys.  However, the change will require some ADE updates to avoid specifying nonexistent keys when mounting the S3 buckets.

**Comment by bsatoriu** [comment]
@gchang there is no EC2 IAM role present in our GCC account with s3 access. We will need to request a new IAM Role, based on the policies of this role, `arn:aws:iam::726330664081:role/MCP-SSM-CloudWatch`, with additional s3 permissions (list/read/write). Let me know if you can request this or if I should email you and Shawn about this.

**Comment by bsatoriu** [comment]
@gchang since the ADE deployment is up and running on GCC, I'm going to move this to Review. I've expanded the scope of #155 to address the remaining GCC-related JupyterLab tasks.

**Comment by oddes** [comment]
Regression on https://ade.uat.maap-project.org/ environment.

1. EDSC is throwing 404 error.

**Comment by bsatoriu** [comment]
@gchang I’ll add another edsc entry to our new jupyterlab config file to make the port number configurable as well. We currently [have it hard coded to 3052 ](https://github.com/MAAP-Project/maap-jupyter-ide/blob/e67ad5f8530683f1391984c376f9deb08cd7a7a6/edsc_extension/src/index.ts#L36). 

@oddes I'll follow up once this is ready to re-test.

**Comment by bsatoriu** [comment]
@oddes the [EDSC issue is fixed](https://github.com/MAAP-Project/maap-jupyter-ide/commit/dd3464b286e6a87ea2494ff89aea4728b18e4951) and ready for re-testing on UAT.

**Comment by oddes** [comment]
Validated with DEV branch, works good.
