### ISSUE TITLE
Copy Download Link does not work on DIT for files in user's private bucket

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#959]
Feature appears to work fine on OPS and works on DIT for files in the user's public bucket.

**Comment by grallewellyn** [comment]
cc @bsatoriu and @sujen1412 
Do you know why this could not be working?

**Comment by grallewellyn** [comment]
This actually is working, the problem is that txt files do not automatically download, instead it just displays the text of the txt file but I was using an empty txt file so I didn't realize
The loading symbol that I was getting was a result of a chrome extension I had enabled JSON Beautifier & Editor. When I disabled this, downloading from my private bucket worked and the network request was now successful
