### ISSUE TITLE
Update custom jupyter extensions to jupyterlab 4

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#979]
DoD:
- [x] development install works for all extensions
- [ ] new pip packages with major versions bumped

**Comment by grallewellyn** [comment]
Using the image you created @marjo-luc mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:jlab4-upgrade
`jupyter labextension list` gives:
<img width="1031" alt="Screenshot 2024-05-07 at 11 12 07 AM" src="https://github.com/MAAP-Project/Community/assets/114033465/e7189e85-7580-4aed-afb7-9d59f7c57371">
And a fresh vanilla environment with our current v3.1.5 release gives: 
<img width="1006" alt="Screenshot 2024-05-07 at 11 12 56 AM" src="https://github.com/MAAP-Project/Community/assets/114033465/dd74e6f8-74ab-4116-8a5c-d0b48440c7ca">

This is something we should look into right? All extensions should be enabled? maap help jupyter extension still works with your image though so I am not sure what the extension not being enabled is really doing

**Comment by marjo-luc** [comment]
@grallewellyn The extensions are all enabled. Are you concerned about the red x'es? I believe they indicate there are newer versions of the packages available.

**Comment by grallewellyn** [comment]
Ah okay that makes sense, I was trying to find documentation about what the red Xs meant but couldn't (I guess enabled in green followed by a red X would be a bad design to show the extension is actually disabled lol)

**Comment by marjo-luc** [comment]
All extensions have been updated and published to test pypi. PR's are open and ready for review.

**Comment by grallewellyn** [comment]
@marjo-luc Is this branch current with the test extensions? https://github.com/MAAP-Project/maap-workspaces/tree/feature/jlab4-upgrade I can do my testing there

**Comment by marjo-luc** [comment]
@grallewellyn Yes. Here is the image you can use in DIT:
`mas.dit.maap-project.org/root/maap-workspaces/jupyterlab3/vanilla:jlab4-upgrade`

**Comment by grallewellyn** [comment]
I tested and these things didn't work:
- Getting the presigned s3 url for a file in my-private-bucket
<img width="669" alt="Screenshot 2024-05-22 at 3 09 41 PM" src="https://github.com/MAAP-Project/Community/assets/114033465/90a2bc16-1da1-4267-8b77-fac4ee7c67aa">

- pasting granule search results for EDSC & executing the other EDSC paste statements- this is happening in a fresh environment too and I think the problem is with the new deployment of setting env variables. I made a ticket to look into it: https://github.com/MAAP-Project/edsc-jupyter-extension/issues/12 so this isn't affecting this ticket 

These things worked:
- submitting and cancelling a job 
- submitting a job from a notebook 
- sorting/ filtering jobs
- registering an algorithm 
- launching earthdata search 
- maap libs pasting maap-py install
- pushing to a git repo
- memory extension

Can we add back in 
```
RUN npm install jupyterlab-plotly@5.5.0
RUN jupyter labextension disable @jupyterlab/apputils-extension:announcements
```
and 
```
RUN jupyter lab build && \
    jupyter lab clean && \
    jlpm cache clean && \
    npm cache clean --force && \
    rm -rf $HOME/.node-gyp && \
    rm -rf $HOME/.local
```
For testing or is there a reason those are removed?

**Comment by marjo-luc** [comment]
@grallewellyn I'll add those back in before I open the PR. 

Do we want to pull the plotly package into the shared environment.yaml?

**Comment by grallewellyn** [comment]
@marjo-luc Yes that is a good idea. Should I push that change to your `feature/jlab4-upgrade` branch?

**Comment by marjo-luc** [comment]
Sure -- thank you, @grallewellyn

**Comment by grallewellyn** [comment]
We are already installing `plotly` as a conda package in our jupyterlab3 environment.ymls. The conda package page for `plotly` links to the same git repo as the npm package `jupyterlab-plotly`. I don't think we need to make a change, I think we can just remove the `jupyterlab-plotly` install from the jupyterlab3 dockerfile 
I tested this by building the images, and `jupyterlab-plotly` is present for `jupyter labextension list`
I will upgrade the version of `plotly` in my `feature/update-packages` branch

**Comment by grallewellyn** [comment]
Also, the pangeo image fails to build and I believe it is because of the `jupyter_server` version being 2.14.0, so once we deploy the change I suggested today to jupyter server extension, this should work
The R image build gives 
```
maap_jupyter_server_extension | error adding extension (enabled: True): The module 'maap_jupyter_server_extension' could not be found (No module named 'xmltodict'). Are you sure the extension is installed?
#19 5.445     Traceback (most recent call last):
#19 5.445       File "/opt/conda/envs/r/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 322, in add_extension
#19 5.445         extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
#19 5.445       File "/opt/conda/envs/r/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 186, in __init__
#19 5.445         self._load_metadata()
#19 5.445       File "/opt/conda/envs/r/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 201, in _load_metadata
#19 5.445         raise ExtensionModuleNotFound(msg) from None
#19 5.445     jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'maap_jupyter_server_extension' could not be found (No module named 'xmltodict'). Are you sure the extension is installed?
```
Maybe we added `xmltodict` here: https://github.com/MAAP-Project/jupyter-server-extension/blob/develop/pyproject.toml#L25
