### ISSUE TITLE
Update maap-workspaces Dockerfiles to support jupyterlab 4 upgrade

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/ZenHub#980]
Need to update relevant files to install jupyterlab 4.

Jupyter 3.x -> 4.x changelog for convenience:
https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#id102

**Comment by grallewellyn** [comment]
Notes from when I tried to do this before:
I could get the images building successfully, but I was unable to launch the image successfully in the ADE
I had to upgrade some packages to avoid dependency conflicts:
- jupyterlab-git 0.41.0
- nodejs=18.3.0 (is downgrade from what we actually have now so this might not work)

Remember to add another if statement here: https://github.com/MAAP-Project/maap-workspaces/blob/main/jupyterlab3/entrypoint.sh#L171

Debugging steps:
- grab image and run in own docker environment 
- just set up bash and don’t allow it to run entrypoint.sh
- sudo docker run —entrypoint [new_command- bash] [docker_image], this creates the container, this just starts a prompt, then I can manually run entrypoint.sh to see what the error is 
- error probably because Jupyter isn’t starting
- https://phoenixnap.com/kb/docker-run-override-entrypoint

Jupyter server commandline options could also be the problem: https://jupyter-server.readthedocs.io/en/latest/other/full-config.html#options

Errors I fixed:
- `./generate_configs.sh: line 70: envsubst: command not found` was fixed by not using the Maven docker file since Brian added it as a gitlab runner, but it shouldn't have been picking up these jobs. Sujen fixed this problem

**Comment by marjo-luc** [comment]
maap-workspaces has been updated. The CI will now build jupyterlab4 images by default.
